{% set version = "3.6.18" %}

package:
  name: gsw
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gsw/gsw-{{ version }}.tar.gz
  sha256: 16011b2a5fb4441c26928ee7aa2f94d02f93c2953ec150e523517cdc654fc927

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - setuptools_scm
  run:
    - python

test:
  imports:
    - gsw
    - gsw.ice
  commands:
    - pip check
    - pytest --pyargs gsw
  requires:
    - pandas >=2 
    - pip
    - pytest

about:
  home: https://github.com/TEOS-10/GSW-Python/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Gibbs SeaWater Oceanographic Package of TEOS-10

extra:
  recipe-maintainers:
    - efiring
    - ocefpaf
