{% set version = "3.6.17" %}

package:
  name: gsw
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gsw/gsw-{{ version }}.tar.gz
  sha256: e13979e1ba29fd41f63c8a3cbb1c47fe50b602d8ce9357b4008b0c2f6e76c665

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - setuptools_scm
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - gsw
    - gsw.ice
  commands:
    - pip check
    - pytest --pyargs gsw
  requires:
    - pandas >=2 
    - pip
    - pytest

about:
  home: https://github.com/TEOS-10/GSW-Python/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Gibbs SeaWater Oceanographic Package of TEOS-10

extra:
  recipe-maintainers:
    - efiring
    - ocefpaf
