{% set version = "3.6.16" %}

package:
  name: gsw
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gsw/gsw-{{ version }}.tar.gz
  sha256: d24d820c8b43dbf72206cf5e3b0ed800b05aa85ca40afd39c9abd19849714197

build:
  number: 1
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - setuptools_scm
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pip
    - pytest
  imports:
    - gsw
    - gsw.ice
  commands:
    - pip check
    - pytest --pyargs gsw

about:
  home: https://github.com/TEOS-10/GSW-Python/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Gibbs SeaWater Oceanographic Package of TEOS-10

extra:
  recipe-maintainers:
    - efiring
    - ocefpaf
