schema_version: 1

context:
  version: 3.6.19

package:
  name: gsw
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/g/gsw/gsw-${{ version }}.tar.gz
  sha256: 3595b686458d852444ae6f1946d260a7c8f16ba457e9061aa953cf417927423f

build:
  number: 2
  skip: match(python, "<3.8")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: numpy
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - setuptools
    - setuptools_scm
  run:
    - python

tests:
  - python:
      imports:
        - gsw
        - gsw.ice
  - requirements:
      run:
        - pandas >=2
        - pip
        - pytest
    script:
      - pip check
      - pytest --pyargs gsw

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Gibbs SeaWater Oceanographic Package of TEOS-10
  homepage: https://github.com/TEOS-10/GSW-Python/

extra:
  recipe-maintainers:
    - efiring
    - ocefpaf
